name: Example e2e tests

on: [push]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          targets: wasm32-unknown-unknown

      - name: install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - id: get-store-path
        run: echo STORE_PATH=$(pnpm store path) >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        timeout-minutes: 5
        id: cache-pnpm-store
        with:
          path: ${{ steps.get-store-path.outputs.STORE_PATH }}
          key: pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-
            pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Build opaque
        run: pnpm build

      - name: install Playwright browsers
        run: pnpm playwright install --with-deps

      - name: run client-simple-webpack tests
        working-directory: examples/client-simple-webpack
        run: pnpm playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: examples/client-simple-webpack/playwright-report/
          retention-days: 30

      - name: run client-with-password-reset tests
        working-directory: examples/client-with-password-reset
        run: pnpm playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: examples/client-with-password-reset/playwright-report/
          retention-days: 30

      - name: run fullstack-e2e-encrypted-locker-nextjs tests
        working-directory: examples/fullstack-e2e-encrypted-locker-nextjs
        run: pnpm playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: examples/fullstack-e2e-encrypted-locker-nextjs/playwright-report/
          retention-days: 30
