name: Tests

on:
  push:
    branches: [canary]
  pull_request:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          targets: wasm32-unknown-unknown

      - name: install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - id: get-store-path
        run: echo STORE_PATH=$(pnpm store path) >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        timeout-minutes: 5
        id: cache-pnpm-store
        with:
          path: ${{ steps.get-store-path.outputs.STORE_PATH }}
          key: pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-
            pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}

      - run: pnpm install

      - name: Build opaque
        run: pnpm build

      - name: tests
        run: pnpm test
